AGENT_MAX_TURNS = 20
AGENT_MAX_HISTORY_MESSAGES = 60
AGENT_TOOL_RESULT_LIMIT = 8000
AGENT_DEFAULT_TIMEOUT = 1800  # 30 min wall-clock per agent run
AGENT_PER_TURN_TIMEOUT = 600  # 10 min ceiling per single LLM call
AGENT_IDLE_WARN_TURNS = 5  # warn after N consecutive read-only turns
AGENT_IDLE_MAX_TURNS = 10  # abort agent after N consecutive read-only turns
MAX_REPAIR_ATTEMPTS = 5
MAX_REIMPLEMENTATIONS = 3
TEST_OUTPUT_LIMIT = 4000
REPAIR_AGENT_TIMEOUT = 600  # 10 min per repair attempt
QUICK_TEST_TIMEOUT = 60  # pre/post-flight check
MAX_QUALITY_ATTEMPTS = 3
TIMEOUT_PLAN = 600.0  # 10 min for plan phase
TIMEOUT_DEVELOP = 7200.0  # 2 hr for full develop pipeline
TIMEOUT_RUN = 1200.0  # 20 min for run-from-spec
